# Generated by Django 6.0.7 on 2026-09-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (stored on Cloudinary)', null=True, upload_to='profile_pics/'),
        ),
    ]
