# Generated by Django 6.0.7 on 2026-07-10 12:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('business', 'Business')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('transaction_limit', models.DecimalField(decimal_places=2, help_text='Maximum transaction amount', max_digits=12)),
                ('daily_limit', models.DecimalField(decimal_places=2, help_text='Daily transaction limit', max_digits=12)),
                ('monthly_limit', models.DecimalField(decimal_places=2, help_text='Monthly transaction limit', max_digits=12)),
                ('requires_email', models.BooleanField(default=True)),
                ('requires_phone', models.BooleanField(default=True)),
                ('requires_id', models.BooleanField(default=False)),
                ('requires_selfie', models.BooleanField(default=False)),
                ('requires_address', models.BooleanField(default=False)),
                ('requires_business_docs', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['transaction_limit'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('login', 'Login 2FA')], max_length=10)),
                ('code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('email', 'Email Verification'), ('phone', 'Phone Verification'), ('id', 'ID Verification'), ('selfie', 'Selfie Verification'), ('address', 'Address Verification'), ('business', 'Business Verification')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('front_id', models.ImageField(blank=True, null=True, upload_to='verification/id_front/')),
                ('back_id', models.ImageField(blank=True, null=True, upload_to='verification/id_back/')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='verification/selfies/')),
                ('business_document', models.FileField(blank=True, null=True, upload_to='verification/business/')),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('kra_pin', models.CharField(blank=True, max_length=20, verbose_name='KRA PIN')),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('business_reg_number', models.CharField(blank=True, max_length=100)),
                ('physical_address', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
