# Generated by Django 6.0.7 on 2026-09-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='back_id',
            field=models.ImageField(blank=True, help_text='Back of National ID (stored on Cloudinary)', null=True, upload_to='verification/id_back/'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='business_document',
            field=models.FileField(blank=True, help_text='Business registration document (stored on Cloudinary)', null=True, upload_to='verification/business/'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='front_id',
            field=models.ImageField(blank=True, help_text='Front of National ID (stored on Cloudinary)', null=True, upload_to='verification/id_front/'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='selfie',
            field=models.ImageField(blank=True, help_text='Selfie for verification (stored on Cloudinary)', null=True, upload_to='verification/selfies/'),
        ),
    ]
