# Generated by Django 6.0.7 on 2026-07-10 11:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('transaction_type', models.CharField(choices=[('goods', 'Goods'), ('services', 'Services'), ('digital', 'Digital Products'), ('property', 'Property'), ('other', 'Other')], default='goods', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(100)])),
                ('escrow_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(default='mpesa', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=50)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('inspection_period_days', models.IntegerField(default=3)),
                ('delivery_deadline', models.DateTimeField(blank=True, null=True)),
                ('inspection_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('payment_confirmed', 'Payment Confirmed'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', max_length=20)),
                ('seller_delivery_confirmation', models.BooleanField(default=False)),
                ('buyer_receipt_confirmation', models.BooleanField(default=False)),
                ('buyer_satisfaction_confirmation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('is_disputed', models.BooleanField(default=False)),
                ('dispute_reason', models.TextField(blank=True)),
                ('dispute_resolution', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_transactions', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='transaction_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Transaction Message',
                'verbose_name_plural': 'Transaction Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('created', 'Transaction Created'), ('payment_initiated', 'Payment Initiated'), ('payment_received', 'Payment Received'), ('delivery_started', 'Delivery Started'), ('delivery_confirmed', 'Delivery Confirmed'), ('inspection_started', 'Inspection Period Started'), ('buyer_accepted', 'Buyer Accepted'), ('funds_released', 'Funds Released to Seller'), ('completed', 'Transaction Completed'), ('dispute_raised', 'Dispute Raised'), ('cancelled', 'Transaction Cancelled'), ('refunded', 'Payment Refunded')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Transaction Milestone',
                'verbose_name_plural': 'Transaction Milestones',
                'ordering': ['-created_at'],
            },
        ),
    ]
